[[edge_functions]]
    function = "block-bots"
    path = "/*"

[[redirects]]
    from = "/contact"
    to = "/about/#contact"

[[redirects]]
    from = "/hello"
    to = "/about/"

[[redirects]]
    from = "/why"
    to = "/about/#why"

[[redirects]]
    from = "/interests"
    to = "/about/#interests"

[[redirects]]
    from = "/ai"
    to = "/about/#ai"

[[redirects]]
    from = "/credits"
    to = "/colophon"