[[edge_functions]]
    function = "block-bots"
    path = "/*"

[[headers]]
    for = "/.well-known/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"





[[redirects]]
    from = "/contact"
    to = "/about/#contact"

[[redirects]]
    from = "/hello"
    to = "/about/"

[[redirects]]
    from = "/why"
    to = "/about/#why"

[[redirects]]
    from = "/interests"
    to = "/about/#interests"

[[redirects]]
    from = "/ai"
    to = "/about/#ai"

[[redirects]]
    from = "/credits"
    to = "/colophon"

[[redirects]]
    from = "/post/165"
    to = "/post/proper-introductions-and-happy-blaugust"

[[redirects]]
    from = "/post/172"
    to = "/post/its-headless-👻"

[[redirects]]
    from = "/post/177"
    to = "/post/journals"

[[redirects]]
    from = "/post/194"
    to = "/post/eleventy-lessons-learned"

[[redirects]]
    from = "/post/200"
    to = "/post/a-saga-of-light-and-darkness"